version: '3.7'
services:
  dev:
    image: node:lts
    ports:
      - 1234:1234
      - 36533:36533
    volumes:
      - .:/app:delegated
    working_dir: /app/web-client
    command: 
      - yarn
      - run
      - parcel
      - serve
      - --no-cache
      - --hmr-port
      - "36533"
      - index.html
  node-server:
    image: node:lts
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 9090
    command: 
      - npx
      - ts-node
      - node-server.ts
  web:
    image: nginx
    volumes:
      - ./web-client/dist:/usr/share/nginx/html
    ports:
      - 80
  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
    command:
      - envoy 
      - -c
      - /etc/envoy/envoy.yaml
      - -l trace
      - --log-path /dev/stdout

  protoc-gen-grpc-web:
    build:
      context: .
      target: protoc-gen-grpc-web
    volumes:
      - .:/app
    working_dir: /app
    command:
      - protoc
      - -I=.
      - echo.proto
      - --js_out=import_style=commonjs,binary:protoc-gen-grpc-web
      - --grpc-web_out=import_style=typescript,mode=grpcwebtext:protoc-gen-grpc-web 
  grpc_tools_node_protoc_ts:
    build:
      context: .
      target: grpc_tools_node_protoc_ts
    volumes:
      - .:/app
    working_dir: /app
    command: 
      - grpc_tools_node_protoc
      - -I.
      - echo.proto
      - --js_out=import_style=commonjs:grpc_tools_node_protoc_ts
      - --grpc_out=grpc_tools_node_protoc_ts
      - --ts_out=grpc_tools_node_protoc_ts
  ts-protoc-gen-node:
    build:
      context: .
      target: ts-protoc-gen
    volumes:
      - .:/app
    working_dir: /app
    command:
      - grpc_tools_node_protoc
      - -I.
      - echo.proto
      - --js_out=import_style=commonjs:ts-protoc-gen-node
      - --grpc_out=ts-protoc-gen-node
      - --ts_out=service=grpc-node:ts-protoc-gen-node

  ts-protoc-gen-web:
    build:
      context: .
      target: ts-protoc-gen
    volumes:
      - .:/app
    working_dir: /app
    command:
      - grpc_tools_node_protoc
      - -I.
      - echo.proto
      - --js_out=import_style=commonjs:ts-protoc-gen-web
      - --grpc_out=ts-protoc-gen-web
      - --ts_out=service=grpc-web:ts-protoc-gen-web