version: '3.7'
services:
  server:
    build:
      context: .
      target: chatd
    command:
      - --host=0.0.0.0
      - --port=9090
  chat:
    build:
      context: .
      target: chat
    command:
      - --host=server
      - --port=9090
      - getMessages
