version: '3.7'
services:
  dev:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    command: [ "sleep", "infinity" ]
  server:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 9090:9090
    command: 
      - node
      - node-server.js
  protoc:
    build:
      context: .
      target: protoc