version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: sleep infinity
